baseURL = 'https://aerat.org/'
languageCode = 'en-us'
title = 'Aerat'

theme = 'paper'

[params]
  # color style
  color = 'linen'                           # linen, wheat, gray, light

  # header social icons
  github = 'aerat-org'                 # github.com/YOUR_GITHUB_ID
  name = "Aerat"
  bio = "Aerith and Kat's Blog!"

  [menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "mailto:knykiel@purdue.edu,aerith.netzer@northwestern.edu"
    weight = 10


